// Constant File for Subjects
const subjects = [
    {
        id: 0,
        code: '33130',
        name: 'Mathematics 1',
        creditPoints: 6,
        requisites: '',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 1,
        code: '48230',
        name: 'Introduction to Engineering Projects',
        creditPoints: 6,
        requisites: '',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 2,
        code: '31269',
        name: 'Business Requirements Modelling',
        creditPoints: 6,
        requisites: '',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 3,
        code: '48023',
        name: 'Programming Fundamentals',
        creditPoints: 6,
        requisites: '',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 4,
        code: '33230',
        name: 'Mathematics 2',
        creditPoints: 6,
        requisites: '33130',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 5,
        code: '48024',
        name: 'Programming 2',
        creditPoints: 6,
        requisites: '48023',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 6,
        code: '31282',
        name: 'Systems Testing & Quality Management',
        creditPoints: 6,
        requisites: '',
        availability: ['Spring'],
    },
    {
        id: 7,
        code: '31271',
        name: 'Database Fundamentals',
        creditPoints: 6,
        requisites: '48023',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 8,
        code: '41035',
        name: 'Professional Practice Preparation 1',
        creditPoints: 3,
        requisites: '',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 9,
        code: '68037',
        name: 'Physical Modelling',
        creditPoints: 6,
        requisites: '',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 10,
        code: '31251',
        name: 'Data Structures and Algorithms',
        creditPoints: 6,
        requisites: '48024',
        availability: ['Autumn'],
    },
    {
        id: 11,
        code: '31257',
        name: 'Information System Development Methodologies',
        creditPoints: 6,
        requisites: '31269',
        availability: ['Autumn'],
    },
    {
        id: 12,
        code: '48240',
        name: 'Design and Innovation Fundamentals',
        creditPoints: 6,
        requisites: '33130',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 13,
        code: '41127',
        name: 'Software Design Studio',
        creditPoints: 6,
        requisites: '31257',
        availability: ['Spring'],
    },
    {
        id: 14,
        code: '48250',
        name: 'Economics and Finance for Engineering Projects',
        creditPoints: 6,
        requisites: '',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 15,
        code: '41113',
        name: 'Software Development Studio',
        creditPoints: 6,
        requisites: '31257',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 16,
        code: '41028',
        name: 'Engineering Work Experience',
        creditPoints: 0,
        requisites: '41035',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 17,
        code: '48260',
        name: 'Engineering Project Management',
        creditPoints: 6,
        requisites: '48240',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 18,
        code: '41128',
        name: 'Software Analysis Studio',
        creditPoints: 12,
        requisites: '31251',
        availability: ['Spring'],
    },
    {
        id: 19,
        code: '48433',
        name: 'Software Architecture',
        creditPoints: 6,
        requisites: '48024',
        availability: ['Spring'],
    },
    {
        id: 20,
        code: '41029',
        name: 'Engineering Research Preparation',
        creditPoints: 6,
        requisites: '48260',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 21,
        code: '48270',
        name: 'Entrepreneurship and Commercialisation',
        creditPoints: 6,
        requisites: '',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 22,
        code: '41055',
        name: 'Professional Experience Review',
        creditPoints: 3,
        requisites: '41028',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 23,
        code: '41030',
        name: 'Engineering Capstone',
        creditPoints: 6,
        requisites: '41029',
        availability: ['Autumn', 'Spring'],
    },
    {
        id: 24,
        code: '41129',
        name: 'Software Innovation Studio',
        creditPoints: 12,
        requisites: '41113',
        availability: ['Spring'],
    },
];

export default subjects;
